import { Box, Button, Container, Text, Title } from "@mantine/core";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Usuarios</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={() => ({
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        })}
      >
        <Title>Usuarios</Title>
        <Link href={"/create"}>
          <Button>Agregar</Button>
        </Link>
      </Box>
    </>
  );
};

export default Home;
